name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  go_router: ^17.0.0
  pinput: ^6.0.1
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  flutter_svg: ^2.2.3
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^2.0.1
  uuid: ^4.5.2
  collection: ^1.19.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
